### ISSUE TITLE
vLLM utilization drops from 80% to 15% with Qwen3-Omni-30B-A3B-Thinking

### ISSUE THREAD

**Issue by ufukpage** [QwenLM/Qwen3-Omni#52]
### Description

Hi,

I have been testing the Qwen3-Omni-30B-A3B-Thinking model using the math problems notebook: https://github.com/QwenLM/Qwen3-Omni/blob/main/cookbooks/image_math.ipynb.

I am experiencing a strange issue on an H100 GPU. After about 1-2 minutes of generation, the vLLM utilization drops significantly from 80% down to 15%.

I have never experienced such a case in vLLM before. I am using the required vLLM version specified in the README: https://github.com/wangxiongts/vllm/.

Is this drop in GPU utilization expected behavior, or has anyone else encountered this?

### Reproduction

https://github.com/QwenLM/Qwen3-Omni/blob/main/cookbooks/image_math.ipynb

### Logs

```shell

```

### Environment Information

H100 GPU, vllm version: https://github.com/wangxiongts/vllm/

### Known Issue

- [ ] The issue hasn't been already addressed in Documentation, Issues, and Discussions.

**Comment by kyr0** [comment]
Can you reproduce the same issue with this containerized deployment variant? I'm wondering if it happens here too. Didn't try the Thinking model yet, probably missing some vLLM args... 
https://github.com/kyr0/qwen3-omni-vllm-docker/blob/main/start.sh#L137

https://github.com/kyr0/qwen3-omni-vllm-docker/blob/main/Dockerfile#L8

I'm trying to create a deployment that "just works" for everything supported. Already fixed the chat template for multi-tool use..

I'll also push some demo code soon using vLLM endpoints for the cookbook cases as I already implemented quite a bunch

**Comment by wangxiongts** [comment]
Have you observed the output tps information, and if using vllm V1 version from https://github.com/vllm-project/vllm/pull/25550, would this phenomenon still occur?

**Comment by bmwas** [comment]
@ufukpage I am facing this issue as well.Did you ever find out why this is happening? Thank you.

**Comment by hsliuustc0106** [comment]
please check with vllm-omni: https://github.com/vllm-project/vllm-omni/tree/main/examples/online_serving/qwen3_omni
